version: "3.3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongo-volume2:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:latest
    container_name: mongoexpress
    ports:
      - 8082:8081
    links:
      - mongodb
    depends_on:
      - mongodb